[FILTER]
    Name grep
    Match *-firelens-*
    Exclude log ^(?=.*ELB-HealthChecker\/2\.0).*$

# [OUTPUT]
#     Name   cloudwatch_logs
#     Match  *
#     region ap-northeast-1
#     log_group_name /aws/ecs/firelens/web_server
#     log_stream_name from-fluentbit
#     auto_create_group true

[OUTPUT]
    Name   kinesis_firehose
    Match  *
    region ap-northeast-1
    delivery_stream firelens-delivery-stream
